apiVersion: v1
appVersion: "2.0"
version: "1.2.1"
description: A tool to log k8s events to stdout in JSON
home: https://github.com/max-rocket-internet/k8s-event-logger
name: k8s-event-logger
maintainers:
- name: max-rocket-internet
  email: max.williams@deliveryhero.com
engine: gotpl
icon: https://github.com/kubernetes/kubernetes/raw/master/logo/logo.png
keywords:
- events
- logging
- auditing
sources:
- https://github.com/max-rocket-internet/k8s-event-logger
